function love.conf(t)
    -- t.identity = nil                    -- The name of the save directory (string)
    -- t.appendidentity = false            -- Search files in source directory before save directory (boolean)
    t.version = "11.5"         -- The LÖVE version this game was made for (string)
    t.console = true
    t.window.title = "postr"   -- The window title (string)
    t.window.icon = nil        -- Filepath to an image to use as the window's icon (string)
    t.window.borderless = true -- Remove all border visuals from the window (boolean)
    t.modules.joystick = false -- Enable the joystick module (boolean)
    t.modules.keyboard = true  -- Enable the keyboard module (boolean)
    t.modules.physics = false  -- Enable the physics module (boolean)
    t.modules.thread = false   -- Enable the thread module (boolean)
    t.modules.touch = false    -- Enable the touch module (boolean)
    t.modules.video = false    -- Enable the video module (boolean)
end
